stages:
  - build

create_file_job:
  stage: build
  image: alpine
  script:
    - echo "Building..."
    - mkdir build
    - touch build/somefile.txt

test_file:  
  image: alpine
  script:
    - test -f build/somefile.txt
   