image: node:16.19.0

stages:
  - build
  - test

create_file_job:
  stage: build
  image: alpine
  script:
   npm install
  artifacts:
    paths:
      - build/

test_file:
  stage: test
  image: alpine
  script:
    - test -f build/somefile.txt
  dependencies:
    - create_file_job